apiVersion: 1
datasources:
  - name: Airflow Metadata
    uid: airflow_metadata
    type: postgres
    access: proxy
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: airflow
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
